/**
 * 
 */
package com.java.yxt.base;

/**
 * @Description 基础校验状态码定义
 * @author lfl
 * @date 2020年8月26日
 */
public enum ValidationEnum implements IStatusEnum {
	CREATE_USER_IS_BLANK(10001, "创建人不能为空"), SENSITIVE_TYPE_WORD_EXIST(11001, "该类别下敏感词已经存在"),
	SENSITIVE_WORD_IS_BLANK(11002, "敏感词不能为空"), CATEGORY_IS_BLANK(11003, "敏感词不能为空"),
	SENSITIVE_TYPE_IS_BLANK(11004, "敏感词类别不能为空"), SENSITIVE_WORD_ID_IS_BLANK(11005, "敏感词类别不能为空"),
	SENSITIVE_WORD_STATUS_IS_BLANK(11006, "敏感词状态不能为空"), COTAIN_SENSITIVE_WORD(11007, "内容包含敏感词"),
	UPLOADFILE_CUSTOMER_NOTEXISTS(11008, "上传文件格式错误，请上传文件名前缀为customer的xls类型文件"),
	UPLOADFILE_INPUTSTREAM_ERROR(11009, "读导入文件流异常"), UPLOADFILE_EMPTY(11010, "导入文件内容为空"),
	EXPORTFILE_OUTPUTSTREAM_ERROR(11011, "导出文件流异常"), ADD_CUSTOMER_ORGANIZATION_ERROR(11012, "添加客户同步添加组织失败"),
	TERMINAL_USERNAME_MSISDN_EXISTS(11013, "用户msisdn已存在"),
	CUSTOMER_CUSTOMER_CODE_EXISTS(11014, "客户编码已存在"),
	CUSTOMER_CUSTOMER_STATUS_INVALID(11015, "客户状态为无效"),
	UPLOADFILE_TERMINAL_NOTEXISTS(11016, "上传文件格式错误，请上传文件名前缀为terminaluser的xls类型文件"),
	UPLOADFILE_TERMINALWHITE_NOTEXISTS(11017, "上传文件格式错误，请上传文件名前缀为terminalwhite的xls类型文件"),
	UPLOADFILE_TERMINALBLACK_NOTEXISTS(11018, "上传文件格式错误，请上传文件名前缀为terminalblack的xls类型文件"),
	TERMINAL_USER_STATUS_INVALID(11019, "终端用户状态不正常"), WHITE_TERMINAL_UNIQUE_EXISTS(11020, "终端MSISDN、业务标识已存在，请更新"),
	BLACK_TERMINAL_UNIQUE_EXISTS(11021, "MSISDN、主被叫类型、限制等级已存在，请更新"), UPLOADFILE_ERROR(11022, "上传文件格式不合法"),
	UPLOADFILE_MSISDN_ERROR(11023, "MSISDN字段数据有误"), BLACK_SP_UNIQUE_EXISTS(11024, "客户名称，业务标识，主被叫类型已存在，请更新"),
	UPLOADFILE_CUSTOMERCODE_NOTEXISTS(11025, "客户名称有误或不存在"),
	UPLOADFILE_DATE_ERROR(11026, "上传时间格式有误，请按照yyyy-MM-dd HH:mm:ss格式填入"),
	UPLOADFILE_IMSI_ERROR(11027, "上传IMSI格式有误，只能输入字母和数字，并且限制15位字符"),
	UPLOADFILE_URL_ERROR(11028, "上传URL字段数据有误"),
	UPLOADFILE_USERNAME_ERROR(11029, "上传用户名称字段数据有误"),
	UPLOADFILE_SERVICECODE_NOTEXISTS(11030, "业务标识不存在或已被添加"),
	UPLOADFILE_MSISDNCUSTOMER_ERROR(11031, "客户与用户绑定关系不存在"),
	UPLOADFILE_CUSTOMERCODE_ERROR(11032, "上传客户编码字段有误"),
	UPLOADFILE_CUSTOMERNAME_ERROR(11033, "上传客户名称字段有误"),
	UPLOADFILE_IP_ERROR(11034, "上传客户IP字段有误"),
	UPLOADFILE_PHONENUM_ERROR(11035, "上传客户号码字段有误"),
	UPLOADFILE_CUSTOMERTYPE_ERROR(11036, "上传客户属性字段有误"),
	UPLOADFILE_CUSTOMERBUSINESSCODE_ERROR(11037, "上传客户业务代码字段有误"),
	UPLOADFILE_SERVICEWAY_ERROR(11038, "上传客户接入方式字段有误"),
	UPLOADFILE_LEVELSEQ_ERROR(11039, "上传客户优先级顺序字段有误"),
	UPLOADFILE_TERMINALFACTORY_ERROR(11040, "上传终端厂商字段有误"),
	SERVICE_SERVICECODE_CUSTERCODE_NOEXISTS(11041, "根据客户编码和业务标识查不到信息"),
	PRODUCTION_SALECODE_RELATION_NOEXISTS(11042, "没有有效的销售品或销售品未关联有效API"),
	UPLOADFILE_TERMINALTYPE_ERROR(11043, "上传终端类型字段有误"),
	UPLOADFILE_TERMINALSTATUS_ERROR(11044, "上传用户状态字段有误"),
	UPLOADFILE_TERMINALSOURCE_ERROR(11045, "上传数据来源字段有误"),
	UPLOADFILE_CHARGE_ERROR(11046, "上传计费类型字段有误"),
	UPLOADFILE_INDUSTRY_ERROR(11047, "上传行业类型字段有误"),
	UPLOADFILE_LIMIT_ERROR(11048, "上传客户权限字段有误"),
	UPLOADFILE_CUSTOMERSTATUS_ERROR(11049, "上传客户业务状态字段有误"),
	UPLOADFILE_CUSTOMERINDUSTRY_ERROR(11050, "上传客户行业字段有误"),
	UPLOADFILE_LEVEL_ERROR(11051, "上传业务优先级字段有误"),
	UPLOADFILE_SAAS_ERROR(11052, "上传是否开通saas字段有误"),
	UPLOADFILE_USERLEVEL_ERROR(11053, "上传限制等级字段有误"),
	UPLOADFILE_TYPE_ERROR(11054, "上传主被叫类型字段有误"),
	UPLOADFILE_MSISDN_NOTEXISTS(11055, "上传MSISDN用户不存在或状态不正常"),
	UPLOADFILE_CUSTOMERNAME_NOTEXISTS(11056, "上传客户不存在或状态无效"),
	IPWHITE_IP_EXISTS(11057,"当前客户对应的ip已存在"),
	UPLOADFILE_MSISDN_DUPLICATE(11058,"MSISDN数据异常"),
	UPLOADFILE_SERVICECODE_ERROR(11059,"业务标识不存在或已被添加"),
	CUSTOMER_CUSTOMER_NAME_EXISTS(11060, "客户名称已存在"),
	UPLOADFILE_CUSTOMERCODEANDNAME_ERROR(11061,"客户导入更新主键冲突，客户编码和客户名称不一致"),
	PRODUCT_API_NOEXISTS(11062,"销售品没有绑定api信息"),
	SERVICE_SERVICECODE_EXISTS(11063,"业务标识已存在"),
	UPLOADFILE_CUSTOMERNAME_DUPLICATE(11064,"客户名称数据异常"),
	PRODUCTION_SALECODE_EXISTS(11065,"销售品ID已存在"),
	SERVICE_CUSTOMERPRODUCT_EXISTS(11066,"当前客户已订购该商品"),
	PRODUCTION_NAME_EXISTS(11067,"销售品名称已存在"),
	TERMINAL_DEVICE_IMEI_EXISTS(11068,"终端设备IMEI已存在"),
	TERMINAL_DEVICE_MEID_EXISTS(11069,"终端设备MEID已存在"),
	UPLOADFILE_IMEI_ERROR(11070,"上传IMEI字段有误"),
	UPLOADFILE_MEID_ERROR(11071,"上传MEID字段有误"),
	UPLOADFILE_MODEL_ERROR(11072,"上传终端型号字段有误"),
	UPLOADFILE_TERMINALDEVICE_NOTEXISTS(11073, "上传模板文件名错误，请上传前缀为terminaldevice的xls类型文档"),
	TERMINAL_FACTORY_NAME_EXISTS(11074,"终端厂商名称已存在"),
	TERMINAL_FACTORY_NAME_NOTEXISTS(11075,"终端厂商不存在"),
	APICATALOG_EXISTS_CHILD(11076,"API目录存在子目录不允许删除"),
	PRODUCTION_STATUS_ERROR(11077,"销售品状态为无效"),
	UPLOADFILE_SAVEFILE_ERROR(11078,"导入保存文件异常"),
	ENTERPRISESIGNATURE_STASUS_EXISTS(11079,"已经生效的企业签名不能被编辑"),
	SECRET_KEY_EXISTS(11080,"一个客户下只能有一个生效的密钥"),
	SECRET_KEY_STATUS_ERROR(11081,"当前密钥状态为有效，请禁用后再修改！"),
	CUSTOMER_SECRET_KEY_EXISTS(11082,"当前客户已有密钥"),
	MGT_OPT_PLATFORM_API_CATEGORY_IS_NULL(12001, "服务类型不能为空"),
	MGT_OPT_PLATFORM_SERVER_ID_IS_NULL(12002, "平台标识不能为空"), MGT_OPT_PLATFORM_ID_IS_NULL(12003, "id不能为空"),
	MGT_OPT_PLATFORM_DELETE_ID_IS_NULL(12004, "删除主键id不能为空"), TOKEN_EMPTY(12005, "token为空,请重新登录"),
	TOKEN_REDIS_ADMIN_EMPTY(12006, "缓存中不存在登陆人信息，请重新登录"), API_CATALOG_NAME_EXISTS(12007, "API名称已存在"),
	IOT_PLATFORM_SERVICE_ID_EXISTS(12008, "服务标识已存在"),
	MGT_GROUP_TERMINAL_EXCEPTION(13000,"终端分组异常！");
	;

	public int code;
	public String message;

	private ValidationEnum(int code, String message) {
		this.code = code;
		this.message = message;
	}

	@Override
	public int getCode() {
		return code;
	}

	@Override
	public String getMessage() {
		return message;
	}

}
